version: "3.8"

services:
  db:
    image: mysql:5.7
    volumes:
      - ./dockerdata/dbdata:/var/lib/mysql
    restart: always
    env_file: .env

  redis:
    image: redis:latest
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - ./dockerdata/redisdata:/data
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  pma:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8800:80"
    env_file: .env