# Generated by Django 3.1.6 on 2021-02-05 12:37

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('descripcion', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('enlace', models.URLField(blank=True, max_length=255, null=True)),
                ('orden_anual', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.categoria')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nombre', models.CharField(max_length=255)),
                ('archivo', models.FileField(max_length=255, upload_to='')),
                ('pertenece_a', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.documento')),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=255)),
                ('junto_con', models.TextField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField()),
                ('lugar', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('dirige', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Dirige', to='base.participante')),
                ('participan', models.ManyToManyField(blank=True, related_name='Participan', to='base.Participante')),
            ],
        ),
    ]
